//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRepainterForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageRepainterForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка по приложению.
        /// </summary>
        internal static string captionApplicationHelp {
            get {
                return ResourceManager.GetString("captionApplicationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        internal static string captionEror {
            get {
                return ResourceManager.GetString("captionEror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех!.
        /// </summary>
        internal static string captionSuccess {
            get {
                return ResourceManager.GetString("captionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте цвета для обработки изображения!.
        /// </summary>
        internal static string infoAddColorsForProcessing {
            get {
                return ResourceManager.GetString("infoAddColorsForProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте цвета для сохранения палитры!.
        /// </summary>
        internal static string infoAddColorsToSavePalette {
            get {
                return ResourceManager.GetString("infoAddColorsToSavePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите существующую цветовую модель!.
        /// </summary>
        internal static string infoChooseRightColorModel {
            get {
                return ResourceManager.GetString("infoChooseRightColorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не обработали изображение!.
        /// </summary>
        internal static string infoEmptyImageToSave {
            get {
                return ResourceManager.GetString("infoEmptyImageToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение обработано!.
        /// </summary>
        internal static string infoImageFinishedProcessing {
            get {
                return ResourceManager.GetString("infoImageFinishedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В буфере обмена нет изображения!.
        /// </summary>
        internal static string infoNoImageOnClipboard {
            get {
                return ResourceManager.GetString("infoNoImageOnClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Палитра создана!.
        /// </summary>
        internal static string infoPaletteCreated {
            get {
                return ResourceManager.GetString("infoPaletteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Палитра не создана!.
        /// </summary>
        internal static string infoPaletteNotCreated {
            get {
                return ResourceManager.GetString("infoPaletteNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не загрузили палитру!.
        /// </summary>
        internal static string infoPaletteNotUploaded {
            get {
                return ResourceManager.GetString("infoPaletteNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключите режим &quot;Палитра на основе картинки&quot;, для загрузки своей палитры!.
        /// </summary>
        internal static string infoTurnOffImageBasedPalette {
            get {
                return ResourceManager.GetString("infoTurnOffImageBasedPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузите изображение!.
        /// </summary>
        internal static string infoUploadSourceImage {
            get {
                return ResourceManager.GetString("infoUploadSourceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string textDelete {
            get {
                return ResourceManager.GetString("textDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение - Перерисовщик изображений
        ///
        ///Приложение обрабатывает пиксели загруженного изображения, заменяя их более подходящими из палитры для выбранной цветовой модели.
        ///
        ///Изображение для обработки может быть загружено как из файла, так и комбинацией Ctrl+V на главной форме.
        ///
        ///Палитра может быть создана и настроена разными способами.
        ///Вы можете загрузить палитру из файла, настроить ее вручную, а также сделать так, чтобы программа создала её на основе загруженного изображения.
        ///При создании палитры на осно [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string textGetInfo {
            get {
                return ResourceManager.GetString("textGetInfo", resourceCulture);
            }
        }
    }
}
